### ISSUE TITLE
Blacklist does not work on videos

### ISSUE THREAD

**Issue by Earlopain** [zwagoth/e621ng#318]
They are  filtered out fine when searching but if you somehow end up on a post anyways toggling the blacklist simply pauses the video and seeks to the start instead of showing the blacklist placeholder.

**Comment by bitWolfy** [comment]
This is actually the exact opposite problem to #319, funnily enough.
Here, the blacklist tries to jam an image file into a `<video>` element.

IMHO, it would be easier if the blacklisting method was jus replaced wholesale.
Instead of trying to change the image / video source, just hide that element, and display the placeholder image in its own dedicated `<img>`.
