### ISSUE TITLE
The post events page is incomplete

### ISSUE THREAD

**Issue by bitWolfy** [zwagoth/e621ng#346]
I'm talking about pages like this one: https://e621.net/posts/897473/events

It would be really nice to have **all** the moderation events listed there, with timestamps.
* Post deleted
* Post undeleted
* Post approved
* Post unapproved
* Post rating locked
* Post flag created

All of those are already available through mod actions, but it's not possible to search for individual posts there.
I believe that this information should be publicly accessible, both for transparency / accountability, and to be able to establish a timeline of events if there is some confusion about what happened to a post.

**Comment by DonovanDMC** [comment]
> All of those are already available through mod actions

Is rating locking visible via mod actions? Unless it's restricted I haven't seen any recently, and the ones I can see are from [March 2020](https://e621.net/mod_actions?commit=Search&search%5Baction%5D=post_rating_lock)

Side note, is there a reason this doesn't have a json api anymore? It looks like it did years ago, but it was disabled in the commit 164ae7efb90e28c962ab447f001b489c631e9de7, which seems rather permanent at this point. This could be a very useful endpoint to parse as it provides a lot of information you can't get anywhere else, like rating locking (if that wasn't just removed?), post deletions, post replacements, etc

**Comment by Earlopain** [comment]
Rating locks are supposed to be logged, but it looks like that broke somehow. The date is rather suspicious since it's the timerange of the danbooru rebase, chances are it just didn't survive and no one noticed until now.

I'm not 100% sure why they were all disabled, but at least tickets and modactions expose more information in the UI to admins. The information is only hidden during presentation, the api would happily provide the user with everything it can offer.
You also can't search for say all unapprovals for post 123, since the only searchable fields are the action type and creator. Everything else is stored in json which is not queryable, at least not with reasonable speed. ModActions would need some bigger changes to make that possible. Perhaps a subject column, which contains the id of the model which makes sense for that action.

**Comment by DonovanDMC** [comment]
> Rating locks are supposed to be logged, but it looks like that broke somehow. The date is rather suspicious since it's the timerange of the danbooru rebase, chances are it just didn't survive and no one noticed until now.
> 
> I'm not 100% sure why they were all disabled, but at least tickets and modactions expose more information in the UI to admins. The information is only hidden during presentation, the api would happily provide the user with everything it can offer.
> You also can't search for say all unapprovals for post 123, since the only searchable fields are the action type and creator. Everything else is stored in json which is not queryable, at least not with reasonable speed. ModActions would need some bigger changes to make that possible. Perhaps a subject column, which contains the id of the model which makes sense for that action.

I'm asking about json because I'm currently bulk downloading and storing a lot of the version histories of e621 locally to make emitting events and more advanced searches 

I've currently got wiki history, artist history, pool history, and post history (yes, all 28 million entries, which took multiple days)

I'm trying to get a dump of the mod actions to be able to tie in several post events as that's what I was working on last (though based on #362 - my main purpose (checking rating locked) is kinda nullified via that not working - I figure this wouldn't be too bad on my side since I've already dumped the entirety of the post history (though I haven't fully sifted through it yet, since the data is over 40 gigabytes)

**Comment by kiranoot** [comment]
Mod actions can contain private fields, so exposing them directly to json isn't possible right now. It would require going through and creating lists of visible and hidden fields for all versions of mod actions over the years.

**Comment by DonovanDMC** [comment]
> Mod actions can contain private fields, so exposing them directly to json isn't possible right now. It would require going through and creating lists of visible and hidden fields for all versions of mod actions over the years.

That makes sense, a bit disappointing though
