### ISSUE TITLE
Counting issues with `\n` in dtext box

### ISSUE THREAD

**Issue by Earlopain** [zwagoth/e621ng#363]
See https://e621.net/forum_topics/31929

The textarea seems to only contain `\n`, but they are converted to `\r\n` before submitting, thus breaking validation when the text contains a few linebreaks and is close to the limit.

**Comment by Earlopain** [comment]
Can be fixed with something like `textarea.val().replace(/\n/g, "\r\n")`, but pressing enter and the counter incrementing by 2, while technically correct, feels weird. Especially since it is not relevant most of the time. The better option in my opinion would be so write a custom validator which counts `\r\n` as one character and using that everywhere where the dtext counter is getting used.

**Comment by DonovanDMC** [comment]
The acceptance of multiple line ending types also enabled some edits that have absolutely no changes but the line endings, for instance when I create a post, they're LF
when someone else (that is on Windows, because CRLF) edits that post, even if they don't touch anything else about it, but manage to change the line endings: the update is accepted as normal and it's extremely difficult to tell what actually happened with that edit without getting the raw contents and comparing them

Going one way or the other would be nice

*definitely not biased to LF*

**Comment by clragon** [comment]
the `\r\n` endings break my entire app parsing so I specifically have to replace them with `\n` everywhere I parse dtext...

_definitely not biased to LF_

**Comment by Tarrgon** [comment]
Yeah I've gone ahead and made ones with a max length normalize to `\n` as we actually already do this in some places

Notably post sources: https://github.com/e621ng/e621ng/blob/master/app/models/post.rb#L350

which normalize `\r\n` to `\n`.
