### ISSUE TITLE
Wikipage DText doesn't cope with URLs ending in a bracket

### ISSUE THREAD

**Issue by urielfrys** [zwagoth/e621ng#370]
https://e621.net/wiki_page_versions/105786

The page version above has the link to Wikipedia with an additional ) at the end, because otherwise the page doesn't consider the one bracket at the end as a part of the URL.

**Comment by DonovanDMC** [comment]
The way dtext links work is pretty annoying, since there's no closing for them - this inevitably causes a lot of issues like the aforementioned issue

it might be nice if we could have some kind of optional ending (since required would break the vast majority of the site, obviously) - say something like "link text":https://google.com#END# 
Something less clunky of course, but this could be an easier solution than practically not allowing parenthesis in urls, or making things look really weird/clunky

It's also impossible to surround urls with parenthesis since it will consider the second one part of the url

**Comment by Earlopain** [comment]
I dread having to change anything in the dtext parser to be honest. I have no idea how ragel actually works and the syntax is very confusing to me. If I would have to guess the error is probably somewhere here https://github.com/zwagoth/dtext_rb/blob/efc37c7795c53425935245cde57cef2121b4f402/ext/dtext/dtext.rl#L113-L117

**Comment by kiranoot** [comment]
This appears to be an interaction with bracketed style support from the looks of it. Maybe delimited urls could be used here? They are just like normal urls but you surround them with < and >.

For reference, ragel is just "regex"(I will use this term loosely because it's not quite the syntax you're used to such as PCRE) rules that get composed together, and you can tell it to mark specific locations along the match, and then run code when the match completes. They are then built into a basic state machine that lets you scope groups of rules together. So at the end of the day it's just a big switch/case tree of text matching rules with code that runs when a match is found.

http://www.colm.net/files/ragel/ragel-guide-6.10.pdf was what I used to learn about how it behaves.

**Comment by ShadyGuy123** [comment]
> This appears to be an interaction with bracketed style support from the looks of it. Maybe delimited urls could be used here? They are just like normal urls but you surround them with < and >.

Just tested, the brackets worked well: https://e621.net/wiki_page_versions/107030

**Comment by toastythemoose** [comment]
I pulled some examples from the wild using the db export and some regex, not comprehensive, but enough to start thinking on a solution.  For bare links I think the brackets will work quite well.  

For named links that doesn't work, but terminating with # does. 

- Original Broken Link: https://e621.net/wiki_page_versions/75416 
- Brackets don't work, breaks syntax and link formatting: https://e621.net/wiki_page_versions/107129
- Terminate with # does : https://e621.net/wiki_page_versions/107130

In addition to further narrow it down, it's not just an issue with the url terminating with ), but also a space directly after. 

Example where its okay:
- https://e621.net/wiki_pages/26582 i.e. ```https://district9.fandom.com/wiki/District_9_(location),```

In case anybody else wants more examples: [parenTerminatedLinks.csv](https://github.com/zwagoth/e621ng/files/8028829/parenTerminatedLinks.csv)
