### ISSUE TITLE
Tag Edit Limit Showing Negative

### ISSUE THREAD

**Issue by DonovanDMC** [zwagoth/e621ng#371]
I've noticed the tag edit limits are being ignored when I edit something. ~~I do have the Privileged rank, so this may be intended. If it is, there's something to be said about the upload limits page showing a negative amount of remaining edits. I haven't legitimately hit this limit since before I got this rank, so I have no idea if this is something that's a normal occurrence.~~
![image](https://user-images.githubusercontent.com/17226394/151831036-ede0790d-24c7-4181-bfc6-7777635c3fae.png)

~~if this isn't meant to be a thing (which I suspect it isn't) this may have come from a lot of very quick bulk editing via tag scripts~~

The no limits bit seems to be intentional, but it still shows a negative amount.

**Comment by DonovanDMC** [comment]
Looking at it, no limiting *is* intentional based on [the code](https://github.com/zwagoth/e621ng/blob/master/app/models/user.rb#L565), but it still displays a negative amount

**Comment by Earlopain** [comment]
This bit in particular is controlled here https://github.com/zwagoth/e621ng/blob/7c4ecd5ac61adf44d19644edab93a2eaf31d0625/app/models/user.rb#L497-L498, and it's being skipped because of `general_bypass_throttle` which is  true for previleged accounts. Displaying that text just needs to be adjusted in https://github.com/zwagoth/e621ng/blob/7c4ecd5ac61adf44d19644edab93a2eaf31d0625/app/views/users/upload_limit.html.erb#L31-L43, hiding the text like it does for users with unrestricted uploads.
