### ISSUE TITLE
Several Mod Action Types Not In Dropdown

### ISSUE THREAD

**Issue by DonovanDMC** [zwagoth/e621ng#382]
Several of the current mod action types for [/mod_actions](https://e621.net/mod_actions) are not listed in the dropdown, while they are still visible to users. For instance, [post_rating_lock](https://e621.net/mod_actions?commit=Search&search%5Baction%5D=post_rating_lock) seems to be visible to all users, but it isn't listed in the dropdown. I'm able to see it in the dropdown on my own instance (being an admin), so this just seems to be a privilege check going wrong somewhere.

### Actions Not Listed, But Viewable
* `edited_user` (legacy)
* `changed_user_text` - (legacy)
* `created_positive_record` (legacy)
* `created_neutral_record` (legacy)
* `created_negative_record` (legacy)
* `forum_topic_stick`
* `forum_topic_unstick`
* `created_flag_reason`
* `edited_flag_reason`
* `deleted_flag_reason`
* `upload_whitelist_create`
* `upload_whitelist_update`
* `upload_whitelist_delete`
* `wiki_page_unlock`
* `post_move_favorites`
* `post_delete`
* `post_undelete`
* `post_destroy`
* `post_rating_lock`
* `post_unapprove`
* `post_replacement_accept`
* `post_replacement_reject`
* `post_replacement_delete`

### Listed, But Seemingly Not Working
* `set_mark_private`
* `set_update`
* `set_delete`
(there were more that are listed & empty, these just stand out to me since I can't see even my own changes, and they're also empty on my own instance)

These were all tested in incognito without being logged in.

**Comment by Earlopain** [comment]
`set_delete` does seem to work, though the other two don't. Logging only happends when you are not the set owner.
I probably won't add the legacy attributes back since they aren't even filled anymore. `_flag_reason` actions are also legacy, since the flag reasons are just controlled in code nowadays.
Anything regarding posts was migrated to https://e621.net/post_events, so having them in the modactions isn't necessary.
I'll take a look at the rest, they should probably be added to the dropdown.

> For instance, [post_rating_lock](https://e621.net/mod_actions?commit=Search&search%5Baction%5D=post_rating_lock) seems to be visible to all users, but it isn't listed in the dropdown. I'm able to see it in the dropdown on my own instance (being an admin), so this just seems to be a privilege check going wrong somewhere.

The dropdown is the same for every user, regardless of level. Perhaps your instance isn't up to date? https://github.com/zwagoth/e621ng/commit/aa77f1a76a6c0ef915fb80deb5cfc622674891ba is the commit moving things to post_events.

**Comment by DonovanDMC** [comment]
My instance is out of date, but not that far out of date (924e519b4c9d7afc4bd927c7a64979cecb29d787) - something went wrong with merging the upstream in somewhere I'm sure

> The dropdown is the same for every user, regardless of level.

I figured as much, since I didn't see anything anywhere to discriminate against user levels - I just figured I might have missed something since everything is everywhere with ruby

> Anything regarding posts was migrated to https://e621.net/post_events, so having them in the modactions isn't necessary.

This makes sense, especially seeing as the older events were transferred

**Comment by Earlopain** [comment]
I added the missing modaction. The set ones still aren't working because sets consider admins their owner, which means that the modaction doesn't get created. I'll create a separate issue for that.
