### ISSUE TITLE
Disabling the `Referrer` header breaks actions involving POST

### ISSUE THREAD

**Issue by DonovanDMC** [zwagoth/e621ng#390]
I've just recently added an extension to my browser that completely disables sending a `Referrer`, not really for privacy but for another site that didn't work when linked from a specific website (because of the referrer) - this completely broke any features that send off POST requests, I couldn't log in, edit posts, make comments, etc.  THis seems like an intentional feature, but can be very detrimental to privacy minded people since I couldn't even log in with the referrer header disabled.

**Comment by kiranoot** [comment]
To the best of my knowledge, nothing in the e621 application intentionally relies upon the behavior of the Referrer header. However, you are likely tripping the built in CSRF protection by modifying request headers arbitrarily. Since modifying HTTP headers to arbitrary values is not standard behavior for browsers on same origin requests, this isn't something that we will spend time on diagnosing.
