### ISSUE TITLE
Add link to users pending posts on user profiles.

### ISSUE THREAD

**Issue by kiranoot** [zwagoth/e621ng#406]
![example area](https://cdn.discordapp.com/attachments/666421129027518474/974736680768667648/unknown.png)

Somewhere to the right of this seems like it would work. No counter needed, just a link.

**Comment by Podgorica** [comment]
Would it be worth putting `if CurrentUser.can_approve_posts?` on this? I don't see any reason why I would need this feature if I don't have the ability to approve posts.

**Comment by Earlopain** [comment]
I thought about that, I think it also has its uses for normal users. Ultimately it doesn't take up much space, so you can just ignore it.

**Comment by faucetlol** [comment]
I can kinda see the uses for normal users, but not sure if it should be shown on the pages for users with the unrestricted uploads permissions.

It would be only actually return results in a few edge cases like an auto-approved being manually unapproved by janitor+, or unapproved posts existing from before the user was granted the rank.

It doesn't really matter to me much though, since I imagine I'll rarely ever be clicking this button.
