### ISSUE TITLE
Using a custom title when linking tags does not work

### ISSUE THREAD

**Issue by DonovanDMC** [zwagoth/e621ng#431]
As the title says. Using a custom title when linking a set of tags does not work. This can be clearly seen in the [dtext help wiki page](https://e621.net/help/dtext#custom_titles).
![image](https://user-images.githubusercontent.com/17226394/184589159-f62bce90-6912-438a-b0e6-5ad2e7fb3f25.png)

**Comment by Earlopain** [comment]
Yeah, I noticed that too. It's just that I'm not looking forward having to change anything in the dtext parser.

Hopefully it shouldn't be too difficult, just look at what wiki pages are doing and copy that over.

**Comment by faucetlol** [comment]
[It looks like it just isn't in the code at all](https://github.com/zwagoth/dtext_rb/blob/efc37c7795c53425935245cde57cef2121b4f402/ext/dtext/dtext.rl#L122). Looks like it should be pretty easy to use the wiki page one as a basis, but no clue how to actually test stuff out since it's a different repo.

**Comment by Earlopain** [comment]
Looks like I figured out a potential solution in the linked pr. Oveall a smal fix, but since I normally don't do C/Ragel it took me an embarrassingly large amount of time.

I also added a better readme and some docker stuff to make it easier for others to get it up and running.
