### ISSUE TITLE
Webpack not found; e621 will not load

### ISSUE THREAD

**Issue by ssterling** [zwagoth/e621ng#449]
Upon a clean installation per [README](https://github.com/zwagoth/e621ng/blob/master/README.md) instructions, accessing localhost:3000 leads to [an error page](https://github.com/zwagoth/e621ng/files/10158616/Action.Controller.Exception.caught.html.gz) with the key words “Webpacker::Manifest::MissingEntryError in Static#home”.  The manifest is empty; [development.log](https://github.com/zwagoth/e621ng/files/10158639/development.log) shows the following:
```
[PID:8] [Webpacker] Compiling...
[PID:8] [Webpacker] Compilation failed:
yarn run v1.22.19
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

error Command "webpack" not found
```

I tried resolving this with `bundle exec rails webpacker:install` (blindly following [a Stack Overflow answer](https://stackoverflow.com/a/65166138) since I know nothing about Ruby) to no avail; logs looked the same aside from this section:
```
[PID:8] [Webpacker] Compiling...
[PID:8] [Webpacker] Compilation failed:
[webpack-cli] Error [BrowserslistError]: /app contains both .browserslistrc and package.json with browsers
    at /app/node_modules/webpack/node_modules/browserslist/node.js:336:15
    at eachParent (/app/node_modules/webpack/node_modules/browserslist/node.js:49:18)
    at Object.findConfig (/app/node_modules/webpack/node_modules/browserslist/node.js:308:20)
    at Function.loadConfig (/app/node_modules/webpack/node_modules/browserslist/node.js:226:37)
    at Object.load (/app/node_modules/webpack/lib/config/browserslistTargetHandler.js:67:18)
    at getDefaultTarget (/app/node_modules/webpack/lib/config/target.js:19:50)
    at /app/node_modules/webpack/lib/config/defaults.js:132:10
    at F (/app/node_modules/webpack/lib/config/defaults.js:73:15)
    at applyWebpackOptionsDefaults (/app/node_modules/webpack/lib/config/defaults.js:131:2)
    at createCompiler (/app/node_modules/webpack/lib/webpack.js:77:2) {
  browserslist: true
}
```

**Comment by Earlopain** [comment]
Can confirm, I suspect 4640862271cddc7d6191fee4a7ac2ca52fcdfc4d as the culprit. The new alpine version comes with openssl3 which apparently causes issues: https://github.com/webpack/webpack/issues/14532.

I'm going to see if simply updating the packages fixes this issue once I'm home. The js packages haven't been updated in ages and that might just do it.

Revert to cb3d34b650790473906e4375fc726644fabe7bc0 for the time being if you're eager to get it running, that should work.

**Comment by Earlopain** [comment]
Yup, that seems to have done it.

I added a section in the readme https://github.com/zwagoth/e621ng#docker-troubleshooting which explains what to do when the inital setup doesn't work out. In this case it wasn't your fault, but you can still follow along to get it correctly running.

**Comment by ssterling** [comment]
I’m somehow still getting the same exact error, even after rebuilding per new instructions.  Any idea where I should start troubleshooting?

**Comment by Earlopain** [comment]
What is the output of running `docker-compose run --rm e621 bin/webpack`?

**Comment by ssterling** [comment]
Pretty simple:
```console
$ docker-compose run --rm e621 bin/webpack
Starting e621ng_elastic_1   ... done
Starting e621ng_redis_1     ... done
Starting e621ng_memcached_1 ... done
Starting e621ng_postgres_1  ... done
Starting e621ng_iqdb_1      ... done
Creating e621ng_e621_run    ... done
yarn run v1.22.19
error Command "webpack" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: 1
```

**Comment by faucetlol** [comment]
I've also been experiencing the exact same problem, I was holding off on making an issue because I thought it was something _I_ did wrong. My output from running that is also exactly the same.

**Comment by Earlopain** [comment]
That's no good. I'll look into this again tomorrow when I have more time.

**Comment by Earlopain** [comment]
Or maybe today, one last try. How about now? I still had a local node_modules folder which got mounted into docker, which is why it still seemed to work for me. I reverted the offending commit.

The problem I was trying to solve was that you need to manually update the js dependencies if they change after your initial build. But that obviously didn't work out. If anyone has an idea on how I can mount the app directory, but use the node_modules from the build image, that would be appreciated. I tried to move node_modules somewhere else inside the image, but webpacker doesn't care about that.

@faucetlol2 you will need to run `docker-compose run --rm e621 yarn install`  before it will work again. I bumped js packages, and these changes need to somehow be put on the named volume.

**Comment by faucetlol** [comment]
All working again for me now, also had to run `docker-compose run --rm e621 bin/webpack` since the application.css was missing.

**Comment by ssterling** [comment]
I, too, had to run `docker-compose run --rm e621 bin/webpack`, but after a total clean install; maybe that needs put in the README instructions?

**Comment by Earlopain** [comment]
That should happen automatically when the file doesn't exist, I'm assuming it tried to do so from a previous attempt where it wasn't working and just gave up after that. Changing a js/css file would also have forced a rebuild.

Maybe I'll add it to the readme, but it should just work now.

**Comment by Earlopain** [comment]
Ok, it was my fault _again_. 372cb8a1acbd9b3c8f9a6cddfca9a18232d10666 removed `yarn install` from `bin/setup`, since I though it was already taken care of in the dockerfile. But the dockerfile didn't have the correct pwd yet, so it was installing node_modules somewhere else. The second `yarn install` then presumably copied the folder to the correct location, and same with running bin/webpack.

Don't know why i didn't notice that yesterday, sorry about that. Now it really should just work.
