### ISSUE TITLE
Stylesheets are missing source maps

### ISSUE THREAD

**Issue by SuscipiamSingularitatem** [zwagoth/e621ng#464]
The `.map` files appear to exist, at least for the main stylesheet, but the `sourceMappingURL` line is missing.

**Comment by Earlopain** [comment]
Cloudflare was minifying the assets _again_, removing the comment in the process. The sourcemaps should load correctly in the future, probably when the cache expires (however often that might happen).

**Comment by Earlopain** [comment]
~~The latest deploy contained a small js change which means that the assets now properly contain the source map url. Either cloudflares cache doesn't expire or it takes a very long time.~~
Since I only made changes to the application js code, the vendored js/css and application css are still loading the old files. But it's nice to see that the issue will at least be solved eventually.
