### ISSUE TITLE
searching for posts with `description:` only works with one word

### ISSUE THREAD

**Issue by DonovanDMC** [zwagoth/e621ng#496]
(unless you're specifically search for descriptions with underscores)
When searching for posts via `description:` (e.g. `description:*owo_whats_this*`), next to nothing will be returned as the underscores are kept in tact.
![](https://cdn.discordapp.com/attachments/329498711338123268/1092977819669237770/image.png)

This isn't as simple as replacing the underscores with spaces either. I'd have just made a pull request if it was. Replacing the underscores with spaces uses each word as an or condition, due to elasticsearch's parsing/analyzing. Unless searching for just one single word, this makes description searching practically useless.

**Comment by mm12** [comment]
> This isn't as simple as replacing the underscores with spaces either. I'd have just made a pull request if it was. Replacing the underscores with spaces uses each word as an or condition, due to elasticsearch's parsing/analyzing. Unless searching for just one single word, this makes description searching practically useless.

So a fix for this would need us to use something other than ElasticSearch, or just how it is implemented? 
I would also like to note that how `description` works is inconsistent. searching for `description:owo description:meow` is treated as `~description:owo ~description:meow` instead! Also note that description does not "care" where things are in text, as such, `description:*owo_whats_this*` and `description:owo_whats_this` would return the exact same results with the current implementation. 

I am not familiar with how ElasticSearch is implemented or RoR, but is it possible to fix this by replacing _spaces_ with _underscores_ in the _description_ instead of the other way around?

**Comment by Earlopain** [comment]
Forgot that there's an issue for this, fixed in https://github.com/e621ng/e621ng/commit/b2c7b338c0499af073f20821d5907580959f0533. `description:"owo whats this"`. I have also improved metatags in general so that `-` and `~` work as expected.
