### ISSUE TITLE
Redirect replaced MD5s to newest post

### ISSUE THREAD

**Issue by Sasquire** [zwagoth/e621ng#547]
After a post replacement, performing a `md5:...` search will return no results. I consider this undesired behavior when compared to the old method of post replacements (creating a new post). With the current system, users can no longer use the *only* the post search to determine if a file was ever uploaded to e621. They must search both active posts and post replacements for the md5. While it may be strange to have a search for a specific md5 give results which have a different md5, I believe this is the experience a user would want.

**Comment by DonovanDMC** [comment]
While it can be annoying for a post to not show up anymore due to it being replaced, I'd consider that working unexpected behavior from a user perspective. If I put in an md5 I expect to be taken to a post with that md5, or given zero results. The replaced post does not have that md5. If you really want solid reverse image searching, you can run it through [/iqdb_queries](https://e621.net/iqdb_queries)
