### ISSUE TITLE
Upload MD5 Confirmation Does Not Work

### ISSUE THREAD

**Issue by DonovanDMC** [zwagoth/e621ng#552]
No matter how much I've tried, I cannot get `upload[md5_confirmation]` to work. Even if I upload the post, copy the md5 e621ng *tells me the file has*, then try to use it, the upload still fails.
![image](https://github.com/e621ng/e621ng/assets/17226394/72e79cfc-60e1-47e5-a9e9-e51573123293)

The image I tried was https://e621.net/posts/3405794. No matter how I calculate it, the MD5 comes out as `dc3a90deef089384f39e45fdaea96e78`. And no matter how many times I try, the upload gets rejected.

**Comment by Earlopain** [comment]
It's validating this before the md5 has even been set.

Do you have an actual use case for this or did you just stumble through documentation or code? As far as I can tell this has been broken since the danbooru rebase so demand for this feature seems exceptionally low. Danbooru seems to have gotten rid of this feature some time ago as well.

**Comment by DonovanDMC** [comment]
I don't personally have a use case for it, no. I was just testing my library's implementation. I've got no qualms if it's just tossed out, though I can see a usefulness in it to ensure the file is received as it was uploaded.
