### ISSUE TITLE
Compatibility issue with older versions of JS in browser causes all post to be hidden.

### ISSUE THREAD

**Issue by Iemand005** [zwagoth/e621ng#556]
The issue occurs on this line (and other occurencies that define the same property):
https://github.com/e621ng/e621ng/blob/68a57dc70bd2d43399514c3e3fcb10907dd86db4/app/views/layouts/_head.html.erb#L64
For some reason this property is applied to all images on all pages causing the website to appear blank on older browsers. I'm aware most people use modern browsers, but everything works when this property is manually disabled, getting this value either disabled or the javascript used to disable it when using an older browser (by perhaps using a different approach to get the correct query, since I assume the issue is simply caused by a function that isn't supported on old JS versions being used to remove the filter) can extend browser compatibility to pretty much every version of Google Chrome, even the very early ones. 

If anyone wants to try to replicate the issue on their device and inspect it, older versions of chrome (for Android) can be found on [APKMirror](https://www.apkmirror.com/uploads/page/10/?appcategory=chrome). To inspect, plug phone into a computer with Chrome desktop installed, navigate to `chrome://inspect/` on computer and on the mobile device, visit the website and click inspect on the computer. For Windows you can find older builds on [Uptodown](https://google-chrome.en.uptodown.com/windows/versions).

Thanks!

**Comment by Earlopain** [comment]
That CSS you see is part of the blacklist. Everything is hidden initially and only shown through JS after.

JS is already transformed in order to placate older browsers. I'm not too sure on how far back it goes, the browserslist file in the repo here doesn't appear to actually do anything. `forceAllTransforms` for babel is true so it just does everything it can I believe.

The only way to correctly view e6 on these older browsers is to disable javascript. Images will show because of the noscript specific styling. Though of course a bunch of other stuff will stop working because of that

**Comment by Iemand005** [comment]
Thanks for the clarification.
I had noticed that disabling JavaScript does indeed fix the issue where the blacklist is applied to everything (for some reason not on Chrome builds like 18), but the other JavaScript functionality is broken anyways so disabling it doesn't appear to remove any functionality, the only notable difference is that the advertisement banner is twice the width with JS disabled.
I'm sure there are methods to fix this problem, but it's totally fine if left as is since very few people use outdated browsers.
Thank you and have a nice day!
