### ISSUE TITLE
Specify in API docs field datatypes and nullability for safe languages such as Rust or C#.

### ISSUE THREAD

**Issue by AnalogFeelings** [zwagoth/e621ng#619]
The current API docs do not specify the datatypes of each fields except for booleans, which have "(True/False)" appended to their description.

The docs should also specify if a field can be null on certain cases with more clarity.

**Comment by DonovanDMC** [comment]
The on site documentation will always be lacking, both because no one wants to write it, and because a codebase as large and old as e621 will have inconsistencies scattered around everywhere

Your best bet is looking at the [db structure](https://github.com/e621ng/e621ng/blob/master/db/structure.sql) - if the column isn't declared `NOT NULL`, *it theoretically can be null*

For instance, really old post versions don't have an updater
Many old things don't have creation dates (like aliases and implications)

It also has the datatype there - look up documentation for postgresql if a type doesn't make sense
